package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
ssh_authorized_keys:
  - >-
    ssh-rsa AAAAAAAAA=
ca-certs:
  trusted:
  - |
    -----BEGIN CERTIFICATE-----
    AAAAAAAAAAA=
    -----END CERTIFICATE-----
